//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

using UnityEngine;

public class PlayerAnim : MonoBehaviour {

	Animation animCtrl;
	PlayerUnit playerUnit;

	List<Tuple<float, float, string>> runAnimConfig;

	public enum State {
		Undefined,
		Idle,
		Run,
	}

	State state;

	void Awake() {
		state = State.Idle;
		animCtrl = gameObject.GetComponentInChildren<Animation> ();
		playerUnit = gameObject.GetComponent<PlayerUnit> ();
		InitRunAnimConfig ();
	}

	void InitRunAnimConfig() {
		runAnimConfig = new List<Tuple<float, float, string>> ();
		runAnimConfig.Add (new Tuple<float, float, string> (-45, 45, "run_forward"));
		runAnimConfig.Add (new Tuple<float, float, string> (45, 135, "run_left"));
		runAnimConfig.Add (new Tuple<float, float, string> (-135, -45, "run_right"));
		runAnimConfig.Add (new Tuple<float, float, string> (-180, -135, "run_backward"));
		runAnimConfig.Add (new Tuple<float, float, string> (135, 180, "run_backward"));
	}

	void Start() {
		SetState (State.Idle);
	}

	string GetRunAnim(float moveFaceAngleDiff) {
		var target = runAnimConfig.Find (item => item.m1 <= moveFaceAngleDiff && item.m2 >= moveFaceAngleDiff);
		if (target != null) {
			return target.m3;
		}

		Debug.LogError ("No run_anim for angle: " + moveFaceAngleDiff);
		return "run_forward";
	}

	void SetState(State newState) {
		if (newState == State.Idle) {
			animCtrl.CrossFade ("idle");
		} else if (newState == State.Run) {
			float rotationAngle = GetRotationAngle(playerUnit.faceDir, playerUnit.moveDir); 
			string animName = GetRunAnim(rotationAngle);
			animCtrl.CrossFade (animName);
		}

		state = newState;
	}

	void Update() {
		if (state == State.Idle) {
			if (playerUnit.moveDir.sqrMagnitude > 0.01f) {
				SetState (State.Run);
			}
		} else if (state == State.Run) {
			if (playerUnit.moveDir.sqrMagnitude < 0.01f) {
				SetState(State.Idle);
			} else {
				float rotationAngle = GetRotationAngle(playerUnit.faceDir, playerUnit.moveDir); 
				string animName = GetRunAnim(rotationAngle);
				if (animCtrl.IsPlaying(animName) == false) {
					animCtrl.CrossFade(animName);
				}
			}
		}
	}

	float GetRotationAngle(Vector3 v1, Vector3 v2) {
		float a1 = Mathf.Atan2 (v1.z, v1.x) * Mathf.Rad2Deg;
		float a2 = Mathf.Atan2 (v2.z, v2.x) * Mathf.Rad2Deg;

		return Mathf.DeltaAngle(a1, a2);
	}
}

